/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_fu_server_ServerLib */

#ifndef _Included_com_fu_server_ServerLib
#define _Included_com_fu_server_ServerLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fu_server_ServerLib
 * Method:    starpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fu_server_ServerLib_starpServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    closeServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fu_server_ServerLib_closeServer
  (JNIEnv *, jobject);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    sendData
 * Signature: (Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_fu_server_ServerLib_sendData
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    sendCmd
 * Signature: (Ljava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_com_fu_server_ServerLib_sendCmd
  (JNIEnv *, jobject, jstring, jbyte);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    closeClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fu_server_ServerLib_closeClient
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    getClientList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_fu_server_ServerLib_getClientList
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
